t = {'id': 214912, '@id': '214912', '@initialImport': '2023-03-22T19:45:22.519876+00:00',
     '@lastSynced': '2024-03-25T08:50:03.791532+00:00', 'assets': [], 'attachments': False,
     'collection': 'Ethnologisches Museum', 'collectionKey': 'EMAfrika1', 'compilation': 'Afrika',
     'dateRange': 'Von 01.01.1501 n. Chr. bis 31.12.1700 n. Chr.', 'dating': ['16 -17. Jahrundert'],
     'description': 'Historischer Hauptkatalog: „Porcellan, chinesisch, anscheinend ganz rohe Exportware vielleicht des 13.-16. Jahrh., rot und grün bemalt. Von einem Yumbengrab bei Dar-es-Salam.“\r\n\r\nForm: Leicht aufgewölbter Boden mit Standring, aufgewölbter Rand\r\nFarbe: Rot auf weiß\r\nErhaltungszustand: Zusammengeklebt. Kleine Fragmente fehlen.',
     'dimensionsAndWeight': ['Objektmaß: 3,5 x 18,3 x 19 cm'], 'exhibit': False,
     'geographicalReferences': ['Tansania (Land/Region)',
                                'Daressalam (Dar-es-Salaam) (Daressalam (Dar-es-Salam)) (Land/Region)',
                                'Herstellungsort: China (Land/Region)'], 'highlight': False,
     'identNumber': 'III E 4142', 'involvedParties': ['Franz Stuhlmann (29.10.1863 - 19.11.1928), Sammler*in'],
     'materialAndTechnique': ['Porzellan'], 'technicalTerm': 'Teller (Grabbeigabe)',
     'permalink': 'https://id.smb.museum/object/214912/teller-grabbeigabe'}
